output: client.c client_lib/serial.c client_lib/utilities.c client_lib/requests.c client_lib/packet_handler.c ../common/TinyFrame.c
	gcc -o client client.c client_lib/serial.c client_lib/utilities.c client_lib/requests.c client_lib/packet_handler.c ../common/TinyFrame.c -Iclient_lib -I../common
